### ISSUE TITLE
Could not find com.voxeet.sdk:uxkit-firebase:3.1.1

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative-firebase#1]
I have added the following maven dependencies 
maven { url "https://android-sdk.voxeet.com/release" }
maven { url "https://android-sdk.voxeet.com/beta" }
and also in app build.gradle file implementation 'com.voxeet.sdk:uxkit-firebase:3.1.1'
But i get the error that 
> Could not find com.voxeet.sdk:uxkit-firebase:3.1.1.
     Required by:
         project :voxeet_react-native-voxeet-firebase
![image](https://user-images.githubusercontent.com/72122766/110948945-02199300-8368-11eb-8b97-875beec01043.png)

**Comment by codlab** [comment]
There's no need to edit your maven dependencies, those are automatically resolved by the gradle modules. The issue was that the 3.1.1 was released to a private repo and not the public maven one. It's fixed now, you can resync your project
