### ISSUE TITLE
Android: Getting compile time error

### ISSUE THREAD

**Issue by codal-mpawar** [voxeet/voxeet-uxkit-reactnative-firebase#10]
@codlab @4thlabs @FabienLavocat @j12y 
**In Local:**
When we run the application and in compile-time, we get this issue.
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-iid:+.
     Required by:
         project :app
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.bintray.com/voxeet/maven/com/google/firebase/firebase-iid/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/voxeet/maven/com/google/firebase/firebase-iid/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/voxeet/maven/com/google/firebase/firebase-iid/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
               
**In App Center:**
 > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://android-sdk.voxeet.com/release/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://android-sdk.voxeet.com/release/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://android-sdk.voxeet.com/release/com/facebook/react/react-native/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/voxeet/maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/voxeet/maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/voxeet/maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by codlab** [comment]
One of the library or your app is referencing jcenter() which needs to be removed in favor of mavenCentral()

This creates a side effect which triggers this issue

**Comment by codal-mpawar** [comment]
@codlab It's working on local but it's failing in the app center.

**Comment by FabienLavocat** [comment]
Could this - https://github.com/voxeet/voxeet-uxkit-reactnative/issues/54 - be related?
@codal-mpawar your build system should not try to download facebook libraries through our repo. Also, please remove any reference to bintray that you may have in your graddle.
