### ISSUE TITLE
Getstream chat push notification not working

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative-firebase#6]
@FabienLavocat @codlab As we were getting issues with the normal push notifications, same has been happening with the getstream chat push notifications. 
We are using this package https://github.com/GetStream/stream-chat-react-native but the push notifications of this package is not working if i use voxeetSDK . Can you also add changes for its events with this repo ?

**Comment by codlab** [comment]
Can you post the content of the file `android/app/build/intermediates/merged_manifest/debug/out/AndroidManifest.xml` from your project ?

**Comment by tuneerclixlogix** [comment]
Sure @codlab 

[AndroidManifest.txt](https://github.com/voxeet/voxeet-uxkit-reactnative-firebase/files/6355621/AndroidManifest.txt)

**Comment by codlab** [comment]
You haven't the service declared inside https://github.com/voxeet/voxeet-uxkit-reactnative-firebase/blob/master/android/src/main/AndroidManifest.xml which means that you haven't integrated the @voxeet/react-native-voxeet-firebase as described in the README file from this repository

```
npm install @voxeet/react-native-voxeet-firebase --save
```

The other steps have been followed tho : the declaration of the meta-data step has been properly followed 👍

**Comment by codlab** [comment]
Btw, there's an issue in your AndroidManifest file,

```

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="" />
```

Should contain a non empty value + create in your app a notification channel defined with that specific id. For instance, Voxeet's channel ID is VideoConference.

Since you are embedding invertase's push notification library as well as zoOr's react-native-push-library, you have two solutions here.
One could be to follow https://github.com/invertase/react-native-firebase-docs/blob/master/docs/notifications/android-channels.md#android-notification-channels


This should probably resolve the issue we noticed with the cancelled notifications.
But don't forget to integrate `yarn add @voxeet/react-native-voxeet-firebase` since the AndroidManifest shows that the library was not installed.

If it was installed tho, can you copy paste me the updated AndroidManifest.xml file so that I can check everything again?

**Comment by tuneerclixlogix** [comment]
@codlab I did the updates for the channel ids, for creating the new channel i did this
PushNotification.createChannel(
      {
        channelId: "trueflutterChannel",
        channelName: "Trueflutter Channel",
      },
      (created) => console.log(`createChannel returned '${created}'`)
    );
    
 and created firebase json with 
 {
    "react-native": {
        "messaging_android_notification_channel_id": "trueflutterChannel"
    }
}

**Comment by tuneerclixlogix** [comment]
@codlab then i was getting the errors of testappvoxeet not found so i changed the package name with my application com.app.trueflutterdating. Still I am not getting the push notifications . I am attaching the adb logcat file while receiving the invite for conference
[logcatTruflutter.txt](https://github.com/voxeet/voxeet-uxkit-reactnative-firebase/files/6425812/logcatTruflutter.txt)

**Comment by tuneerclixlogix** [comment]
@codlab Also , i tried running the test app but i am getting errors in running it
![image](https://user-images.githubusercontent.com/72122766/117130845-3a64ad00-adbe-11eb-9674-dea609dcc4e0.png)
I also tried installing the @voxeet/react-native-voxeet-firebase package and adding maven { url "https://dl.bintray.com/voxeet/maven/" } in build.gradle file but still facing errors

**Comment by codlab** [comment]
I completely forgot to send the commit update for the test app, if you pull the test app's master branch it will work right away 👍

**Comment by codlab** [comment]
Btw this commit also refers to the latest develop commit (which the package-lock.json did not) which means that the version you tested did not use the develop's commits which fixes the notification.

The logs you sent shows that the notification was indeed received, that's a good sign. But the flow is showing the notification is starting the .MainActivity which shouldn't be the case in the latest version of the library itself. 

Once you update everything, it will normally display the overhead notification, can you pull the master branch + reinstall the develop branch (`npm install --save "git://github.com/voxeet/voxeet-uxkit-reactnative.git#develop"`)

**Comment by tuneerclixlogix** [comment]
Sure @codlab , i will try removing the complete package and install it again with yarn add @voxeet/react-native-voxeet-conferencekit#develop. 
Also now with test app i am getting 
![image](https://user-images.githubusercontent.com/72122766/117147994-6b031180-add3-11eb-9364-f2154191948c.png)

**Comment by tuneerclixlogix** [comment]
Hello @codlab , I updated the package again. Now the call UI comes up when the app was in foreground. But there are still issues when the app is in killed state, in this i get the push notification and when i press on answer the app doesn't opens but i got this crash report in flipper
![image](https://user-images.githubusercontent.com/72122766/117253510-e82a9700-ae64-11eb-88e6-1b03da433461.png)

**Comment by tuneerclixlogix** [comment]
Here are the adb logs for this crash 
[voxeetcrashlog.txt](https://github.com/voxeet/voxeet-uxkit-reactnative-firebase/files/6432397/voxeetcrashlog.txt)

**Comment by codlab** [comment]
You have not the proper meta-data in your android manifest, you need the accepted one (like in the test app 👍)

**Comment by tuneerclixlogix** [comment]
@codlab Do you mean i have to add these in android manifest ?
<meta-data
            android:name="voxeet_incoming_class"
            android:value="com.voxeet.notification.RNIncomingCallActivity" />
        <meta-data
            android:name="voxeet_incoming_accepted_class"
            android:value="com.app.trueflutterdating.MainActivity" />
            
I can't notice any meta-data in this file https://github.com/voxeet/voxeet-uxkit-reactnative-testapp/blob/master/android/app/src/main/AndroidManifest.xml

**Comment by codlab** [comment]
You only need the voxeet_incoming_accepted_class - it will enable your app to start from the notification

**Comment by tuneerclixlogix** [comment]
@codlab 
Yes its working now, but when i answer the call , it opens the app and then call UI is displayed after 4-5 seconds. Can I do something to make it more faster ?

**Comment by codlab** [comment]
If you do like inside the testApp, in « asap » initialization/connection, it will appear faster. Can you track down when the app opens and when the connects calls start and « resolved »?

**Comment by codlab** [comment]
I'm closing the issue since the original issue as been fixed. Regarding the delays, I'm looking forward to have a ticket with more information like timed info, etc... to see where it could be improved in your app and our library
