### ISSUE TITLE
Crash in debug mode and random in release mode apk

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative-firebase#7]
@codlab The crash we discussed on call while working with the debug build with "react-native": "0.63.3" is also occurring with the release apk on random basis when the UI is displayed . 
I am attaching the screenshots and log file for your reference
![image](https://user-images.githubusercontent.com/72122766/117997412-8edccf00-b360-11eb-892f-caec65292a37.png)
![image](https://user-images.githubusercontent.com/72122766/117997428-91d7bf80-b360-11eb-9541-0ec078688ad3.png)
![image](https://user-images.githubusercontent.com/72122766/117997451-9603dd00-b360-11eb-9e8b-8f9153a1c3d9.png)
[releaseCrashLog.txt](https://github.com/voxeet/voxeet-uxkit-reactnative-firebase/files/6467029/releaseCrashLog.txt)

**Comment by codlab** [comment]
Please reopen this issue in the original http://github.com/voxeet/voxeet-uxkit-reactnative repository. Please make sure at the same time that you followed instructions from the https://github.com/voxeet/voxeet-uxkit-reactnative/tree/develop#readme where some modifications are required. I'm looking forward to have more info regarding how it was triggered : from push etc...
