### ISSUE TITLE
iOS build failing with develop branch

### ISSUE THREAD

**Issue by tuneerclixlogix** [voxeet/voxeet-uxkit-reactnative-firebase#8]
@codlab For iOS I am not able to build the app with the develop branch
![image](https://user-images.githubusercontent.com/72122766/118001704-9a31f980-b364-11eb-89a2-96a52a117225.png)

**Comment by codlab** [comment]
Please open this issue in the http://github.com/voxeet/voxeet-uxkit-reactnative repository

make sure as well that you reinstalled the Pods using `npx pod-install`
